server:
  port: 9091
  servlet:
    context-path: /pet-app/

spring:
  application:
    name: USERSSERVICE
  config:
    import: "configserver:http://localhost:9296"
  zipkin:
    base-url: http://localhost:9411/
  data:
    mongodb:
      host: localhost
      port: 27017
      database: petapp
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
  jwt:
    header: Authorization
    cookie: pet-cookie
    secret: pet-app-secret-key
    expiration: 604800
  kafka:
    bootstrap-servers: localhost:9096
