server:
  port: 9092

spring:
  application:
    name: EMAILSERVICE
  config:
    import: "configserver:http://localhost:9296"
    zipkin:
      base-url: http://localhost:9411/
  mail:
    host: smtp.gmail.com
    port: 587
    username: piessedev@gmail.com
    password: SDE333w!
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  kafka:
    bootstrap-servers: localhost:9096